### ISSUE TITLE
Batect doesn't work on Windows

### ISSUE THREAD

**Issue by carloslimasis** [charleskorn/batect#42]
Hi there!

My environment is:
Java: 1.8.0_191
Docker: 18.09.0
Windows 10
GitBash

When I try to run `./batect --version` I have the following error:

> Fatal exception:
java.lang.UnsatisfiedLinkError: A opera▒▒o foi conclu▒da com ▒xito.
        at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
        at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
        at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
        at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
        at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:158)
        at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:89)
        at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
        at batect.os.NativeMethods.<init>(NativeMethods.kt:37)
        at batect.InjectionConfigurationKt$osModule$1$1.invoke(InjectionConfiguration.kt:193)
        at batect.InjectionConfigurationKt$osModule$1$1.invoke(InjectionConfiguration.kt)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:62)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at batect.InjectionConfigurationKt$uiModule$1$4.invoke(InjectionConfiguration.kt:237)
        at batect.InjectionConfigurationKt$uiModule$1$4.invoke(InjectionConfiguration.kt)
        at batect.InjectionConfigurationKt$uiModule$1$$special$$inlined$singletonWithLogger$1.invoke(KodeinLoggingExtensions.kt:33)
        at batect.InjectionConfigurationKt$uiModule$1$$special$$inlined$singletonWithLogger$1.invoke(KodeinLoggingExtensions.kt)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:62)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at batect.InjectionConfigurationKt$uiModule$1$3.invoke(InjectionConfiguration.kt:236)
        at batect.InjectionConfigurationKt$uiModule$1$3.invoke(InjectionConfiguration.kt)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:62)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at batect.Application.runCommand(Application.kt:95)
        at batect.Application.run(Application.kt:55)
        at batect.ApplicationKt.main(Application.kt:36)

I also tried to run batect jar with `java -jar batect-0.23.3.jar --version`, but I had the same problem.

**Comment by charleskorn** [comment]
Unfortunately batect does not yet support Windows, and the error message you're seeing there is a symptom of that. (The error message could be much clearer though, so I'll fix that.)

If you're running Windows 10, batect might work under [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), although I haven't tried it.

Adding Windows support is not a big priority for me at the moment (but it is on my to-do list). If you are interested in providing a PR to add Windows support, I'd be happy to give you some suggestions and provide feedback on the PR as you go.

**Comment by charleskorn** [comment]
This is being tracked in the roadmap, so I'm going to close this for now.

**Comment by charleskorn** [comment]
Hey @carloslimasis, just wanted to let you know that batect now has experimental support for Windows with [v0.34](https://github.com/charleskorn/batect/releases/tag/0.34.0) - please try it out and let me know how you go.
